language: php
php:
- 5.6
- 7.0
- 7.1
cache:
  directories:
  - "$HOME/.composer/cache"
  - vendor
before_install:
- phpenv config-rm xdebug.ini
- composer self-update
install:
- composer install -o --prefer-dist --no-interaction
script:
- composer test
notifications:
  slack:
    secure: lB4OTbVkVWjrL8Bv4VlSfmiremDaMJ0F9MN076NfoN7zToS+xJEKF5iigUJGUofRRyg1IDAvguhgYK3gxxpBFGmFAKqDu/K8vb/fZc8MFwXc3Dm5K2Yvwhf0Ffg8q9QcfDzWF9bp4s8zrDRKsDpSsatFQBDuKPNh5zKnFxeYV78QPdKFHW6gJS+uFSbmpXUsaKRvUzJ1SH1wFNZmFfBS7HYBn6/Byc5ht4IwzL1zGdnWZBVa8t/O6pbvNpBVcHpGpVPcBfub3zxw3peGImqQmrm9g+UfbnQToZ5QnvQ1zTo7IT1QLkAMHrgrBz7qy9aT9TPB1hN0pwNaYLIykmISgiqCCXXLwIZ9hQr7yg4hvamwpv5Mf9yj2OZfTG2AB3lYqN8XX7RltVrezynRU+EPZKDUz0i2sJ26oNzhKamGRJrDZ0EDv/uHxXwr4yPPdPIxCxzTgQofDOFud9PFm1wQJ3RvBK+XOW4RI1d6cn5kvT0c+gkO83yB1iG/ZIUu/svsasZg1fJNfwEvgbai3gCEIMOUZT1NzOHlSlgUkfd4hCLRbglylCTc/XqFVy3KBeepvKvvcdnBKa9SWXxz3L2Gee/9u5YAJ5BXQCEan928gsmXwYkTWUdu7eiHlHtIsY+R2rY0GDZ2NmHbiplP25K995nI7SjTbDMBzM8k6mL+jHY=
